project:
  type: book

book:
  title: "Reproducible Data Processing and Visualization"
  subtitle: "in R and tidyverse"
  author: "Ian Hussey"
  date: today
  chapters:
    - index.qmd
    - chapters/setup.qmd
    - chapters/fundamentals.qmd
    - chapters/reproducible_reports.qmd
    - chapters/loading_data.qmd
    - chapters/the_pipe_and_renaming.qmd
    - chapters/data_transformation_1.qmd
    - chapters/data_transformation_2.qmd
    #- chapters/project_1.qmd
    #- chapters/data_transformation_3.qmd
    - chapters/strings_and_factors.qmd
    - chapters/reshaping_and_pivots.qmd
    - chapters/binding_and_joining.qmd
    #- chapters/project_2.qmd
    - chapters/structuring_projects.qmd
    - chapters/visualization.qmd 
    - chapters/reporting.qmd
    #- chapters/the_linear_model.qmd
    # assignment here?
    # add some sort of appendix notice here?
    - chapters/privacy.qmd
    #- references.qmd
    - chapters/license.qmd
    
# bibliography: references.bib

format:
  html:
    toc: true
    toc_float: true
    code-fold: show
    code-tools: true
    warning: false
    theme: cosmo
    #embed-resources: false
    #highlight: haddock

editor: visual

cover-image: cover.png

