project:
  type: book

book:
  title: "Reproducible Data Processing and Visualization"
  subtitle: "in R and tidyverse"
  author:
    - name: Ian Hussey
      orcid: 0000-0001-8906-7559
      email: ian.hussey@unibe.ch
  date: today
  chapters:
    - index.qmd
    
    - part: "Part I: Setup"
      chapters:
      - chapters/1_setup.qmd
      # - chapters/updating.qmd
      - chapters/2_fundamentals.qmd
      
    - part: "Part II: Wrangling"
      chapters:
      - chapters/3_reproducible_reports.qmd
      - chapters/4_loading_data.qmd
      - chapters/5_the_pipe_and_renaming.qmd
      - chapters/6_data_transformation_1.qmd
      - chapters/7_data_transformation_2.qmd
      - chapters/8_data_transformation_3.qmd
      # - chapters/sum_scores.qmd
      - chapters/9_structuring_projects.qmd
      - chapters/10_strings_and_factors.qmd
      - chapters/11_reshaping_and_pivots.qmd
      - chapters/12_binding_and_joining.qmd
      - chapters/13_sharing_and_privacy.qmd
      
      
    - part: "Part III: Visualization and reporting"
      chapters:
      - chapters/14_visualization.qmd 
      - chapters/15_reporting.qmd
      - chapters/16_the_linear_model.qmd
      
    # - part: "Exercises"
    #   chapters:
    #   - chapters/project_1.qmd
    #   - chapters/project_2.qmd
    #   - chapters/project_3.qmd
    
    - part: "Appendices"
      chapters:
      #- references.qmd
      - license.qmd
    
# bibliography: references.bib

format:
  html:
    toc: true
    toc_float: true
    code-fold: false
    code-overflow: wrap
    code-tools: true
    warning: false
    df-print: kable
    theme:
      light: cosmo
      dark: darkly
    highlight-style:
      light: breeze
      dark: dracula

editor: visual

cover-image: cover.png

