# Lesson plan {.unnumbered}

If delivered as a semester-long course, we suggest the following lesson plan.

### Week 1

Before class:

- [Chapter 1: Setup](chapters/01_setup.qmd)
- [Chapter 2: Fundamentals](chapters/02_fundamentals.qmd)

In class:

- [Discussion of course structure](slides/slides_week_1.pdf)
- Questions about setup, fundamentals
- [Chapter 3: Reproducible reports](chapters/03_reproducible_reports.qmd)

### Week 2

Before class:

- [Chapter 4: Loading, viewing and saving data](chapters/04_loading_data.qmd) 
- [Chapter 5: The pipe and renaming](chapters/05_the_pipe_and_renaming.qmd)

In class:

- Questions about reproducible reports
- Questions about loading data
- Questions about the pipe and renaming
- In-class exercises - [click to download .qmd](exercises/02_to_04_loading_data_in_class_exercises.qmd)

### Week 3

Before class:

- [Chapter 6: Data transformation I](chapters/06_data_transformation_1.qmd) 

In class:

- Questions about Data transformation I
- In-class exercises - [click to download .qmd](exercises/06_data_transformation_1_in_class_exercises.qmd)

### Week 4

Before class:

- [Chapter 7: Data transformation II](chapters/07_data_transformation_2.qmd)

In class:

- Questions about Data transformation II
- In-class exercises - [click to download .qmd](exercises/07_data_transformation_2_in_class_exercises.qmd)

### Week 5

Before class:

- [Chapter 8: Data transformation III](chapters/08_data_transformation_3.qmd)

In class:

- Questions about Data transformation III
- In-class exercises - [click to download .qmd](exercises/08_data_transformation_3_in_class_exercises.qmd)

### Week 6

Before class:

- [Chapter 9: Structuring projects](chapters/09_structuring_projects.qmd)
- [Chapter 10: Data types](chapters/10_data_types.qmd)

In class:

- Questions about structuring projects
- Questions about data types
- Overview of assignment 1 (wrangling)
- In-class exercises - [click to download .qmd](exercises/10_data_types_in_class_exercises.qmd)

### Week 7

Before class:

- [Chapter 11: Strings and factors](chapters/11_strings_and_factors.qmd)
- [Chapter 12: Reshaping and pivots](chapters/12_reshaping_and_pivots.qmd)

In class:

- Questions about strings and factors
- Questions about reshaping and pivots
- In-class exercises - [click to download .qmd](exercises/11_strings_and_factors_in_class_exercises.qmd)
<!-- - In-class exercises - [click to download .qmd](exercises/12_reshaping_and_pivots_in_class_exercises.qmd) -->

### Week 8

Before class:

- [Chapter 13: Binding and joining](chapters/13_binding_and_joining.qmd)

In class:

- Questions about binding and joining
<!-- - In-class exercises - [click to download .qmd](exercises/13_binding_and_joining_in_class_exercises.qmd) -->

### Week 9

Before class:

- [Chapter 14: Sharing and privacy](chapters/14_sharing_and_privacy.qmd)

In class:

- Questions about sharing and privacy
- Lecture and exercise: Intro to GitHub, diffs
<!-- - In-class exercises - [click to download .qmd](exercises/14_sharing_and_privacy_in_class_exercises.qmd) -->

### Week 10

Before class:

- Dattani, S. (2025) Saloni's guide to data visualization. https://www.scientificdiscovery.dev/p/salonis-guide-to-data-visualization
- Saloni's data visualizations while working at *Our World In Data*: https://ourworldindata.org/team/saloni-dattani

In class:

- Lecture: Principles of visualization
- In this course, this is often a guest lecture by Dr. Saloni Dattani.
  - Founding editor of [Works in Progress](https://worksinprogress.co/our-authors/saloni-dattani/)
  - See her TED talk [here](https://www.youtube.com/watch?v=6eYEi9tN6Og)
  - Her podcast, [Hard Drugs](https://harddrugs.worksinprogress.co/), is a show about "medical innovation, how to speed it up, how to scale it up, and how to make sure lifesaving tools reach the people who need them the most". 
  

### Week 11

Before class:

- [Chapter 15: Visualization](chapters/15_visualization.qmd)
- [Chapter 16: Reporting](chapters/16_reporting.qmd)

In class:

- Questions about reporting
- Questions about ggplot2 for visualization
- Overview of assignment 2 (plotting)
<!-- - In-class exercises - [click to download .qmd](exercises/15_to_16_reporting_in_class_exercises.qmd) -->

### Week 12

Before class:

- [Chapter 17: The linear model](chapters/17_the_linear_model.qmd)

In class:

- Questions about the linear model
- Questions about the assignments
<!-- - In-class exercises - [click to download .qmd](exercises/17_the_linear_model_in_class_exercises.qmd) -->

### Week 13 + 14

Oral examinations

