---
title: "How to use this book"
format:
  html:
    toc: true
    toc_float: true
    code-fold: show
    code-tools: true
    self-contained: true
---



## Other learning resources

-   You can find cheatsheets in the /resources folder \[\TODO add link\]
-   The Open Source textbook [Data Skills for Reproducible Research](https://psyteachr.github.io/reprores-v3/) (DeBruine et al.) is very good, e.g., its sections on [dplyr](https://psyteachr.github.io/reprores-v3/dplyr.html) and [tidyr](https://psyteachr.github.io/reprores-v3/tidyr.html).
-   Allison Horst's interactive web app to learn dplyr is great: <https://allisonhorst.shinyapps.io/dplyr-learnr/#section-welcome>.
-   The Open Source textbook R for Data Science (aka, [Wickham's R4DS](https://r4ds.hadley.nz/)) is also very good, if a little dryer. Hadley Wickham is the main developer of the "tidyverse" set of packages, including dplyr, tidyr, ggplot2, stringr, lubridate, and others. See its [section on data transformation](https://r4ds.hadley.nz/data-transform).
    -   The entire second edition of the book is available at <https://r4ds.hadley.nz/>.
-   Garrick Aden-Buie's tidyexplain is great for understanding how tidyr's pivot functions work: <https://github.com/gadenbuie/tidyexplain>
-   datasciencebox.org has good interactive tutorials, but they are more useful for practicing processing and visualization skills once you've already learned the functions
    -   ggplot2 <https://minecr.shinyapps.io/dsbox-01-edibnb/>
    -   ggplot2, pipe, mutate <https://minecr.shinyapps.io/dsbox-02-accidents>
    -   ggplot2, pipe, select, arrange, summarize, count, filter <https://minecr.shinyapps.io/dsbox-03-collegemajors>
    -   count, arrange, summarize <https://minecr.shinyapps.io/dsbox-04-legosales/>
-   If you'd like video content, datasciencebox.org also has it: <https://datasciencebox.org/02-exploring-data>
